# Generated by Django 3.2 on 2021-05-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='res',
            field=models.TextField(default='cs', max_length=1000),
            preserve_default=False,
        ),
    ]
